
# === Basic App Settings ===
spring.application.name=AlumniConnect
server.port=8080

# === MongoDB (Local + GitHub Actions) ===
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb://localhost:27017/alumni_connect

# === Session Management (optional but good) ===
spring.session.store-type=mongodb

# === Logging ===
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

google.client.id=106935571894-vfebl26ecj13g742e54e2e5ps050e46e.apps.googleusercontent.com
jwt.secret=056ec4967aa3edd9d2349cb7820e80f3
file.upload.base-dir=C:/Users/ANSHUL/ALUMNI-CONNECT/ALUMNI-CONNECT
